### ISSUE TITLE
JSON Request Error

### ISSUE THREAD

**Issue by dsully** [james1236/backseat.nvim#12] opened 2023-04-06 03:02 UTC
Backseat is giving me a JSON request error - I've tried with `curl` 7.85.0 and 8.0.1:

```
Backseat > Sending main.py (split into 2 requests) and waiting for response...
Backseat > {
    "error": {
        "message": "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please send an email to support@openai.com and include any relevant code you'd like help with.)",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}```

Also, instead of encoding the string, would it be better to write the request out to a temporary file and point `curl` at it to avoid potential shell issues?

Let me know what else I can get you for debugging here.

Thanks

**Comment by james1236** [comment] 2023-04-06 13:02
Thanks. Is this windows or linux? Does it do this for all files you've tried?

**Comment by dsully** [comment] 2023-04-06 14:06
Linux and macOS. Yes, for all the files I’ve tired.

**Comment by james1236** [comment] 2023-04-06 22:15
> Linux and macOS. Yes, for all the files I’ve tired.

Did that fix it?

**Comment by dsully** [comment] 2023-04-07 16:45
Maybe? I'm getting a `OpenAI Error: You exceeded your current quota, please check your plan and billing details.` error now, using `gpt-3.5-turbo`, even though I'm nowhere near the quota.

**Comment by james1236** [comment] 2023-04-07 16:55
I can't think of a way that open ai error could be caused by the plugin so I'll close this, you can test chat completion here: https://platform.openai.com/playground?mode=chat&model=gpt-3.5-turbo

**Closed as completed by james1236** 2023-04-07 16:55 UTC
